home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns =[
    path('', views.index, name='index')
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns =[
    path('', views.homepage, name='homepage'),
    path('homepage/', views.homepage, name='homepage'),
    path('blogs/', views.blogs, name='blogs'),
    path('about_me/', views.about_me, name="about_me"),
    path('blogs/agustus17th/', views.agustus17th, name='blogs/agustus17th'),
    path('liat_matkul/', views.liat_matkul, name='liat_matkul'),
    path('tambah_matkul/', views.create_matkul, name="tambah_matkul"),
    path('matkul/<pk>/', views.matkul, name="matkul"),
    path('hapus_matkul/<pk>/', views.delete_matkul, name="hapus_matkul")
]

story7/urls.py
from django.urls import path
from . import views

app_name = 'story7'

urlpatterns =[
    path('', views.index, name='index')
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns =[
    path('', views.index, name='index'),
    path('data/', views.data, name='data'),
    path('detail/<pk>/', views.detail, name="detail"),
]

story9/urls.py
from django.urls import path
from . import views

app_name = 'story9'

urlpatterns =[
    path('', views.index, name='index'),
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logOut, name="logout"),
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include
from story8.views import data

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story1/', include('story1.urls')),
    path('story3/', include('story3.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    #path('data/', data),
]

story9/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
# Create your models here.
class AccountCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder':'  Enter username...'})
        self.fields['email'].widget.attrs.update({'placeholder':'  Enter email...'})
        self.fields['password1'].widget.attrs.update({'placeholder':'  Enter password...'})        
        self.fields['password2'].widget.attrs.update({'placeholder':'  Repeat password'})

story9/forms.py
from django.forms import ModelForm
#from django.contrib.auth.forms import UserCreationForm
from .models import AccountCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(AccountCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

story9/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from datetime import datetime
import json

# Create your views here.
def index(request):
    return render(request, 'story9/index.html')

def registerPage(request):
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun dengan nama ' + form.cleaned_data.get('username') + ' berhasil dibuat')
            return redirect('story9:login')
    else:
        form = CreateUserForm()
    

    return render(request, 'story9/register.html', {'form' : form})

def loginPage(request):
    context = {}
    
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            context = compileInformation(user)
            for key, value in context.items():
                request.session[key] = value
            return redirect('story9:index')
        else:
            messages.info(request, 'Username atau password salah')
    
    return render(request, 'story9/login.html', context)

def logOut(request):
    logout(request)
    return redirect('story9:login')

def compileInformation(user):
    temp = dict()
    if user.first_name == "":
        temp['first_name'] = "-"
    if user.last_name == "":
        temp['last_name'] = "-"
    if user.is_staff:
        temp['peran'] = "Staff"
    else:
        temp['peran'] = "User"
    date_joined = str(user.date_joined).split(".")[0]
    last_login = str(user.last_login).split(".")[0]
    date_joined = datetime.strptime(date_joined, "%Y-%m-%d %H:%M:%S")
    last_login = datetime.strptime(last_login, "%Y-%m-%d %H:%M:%S")
    temp['date_joined'] = str(date_joined)
    temp['last_login'] = str(last_login)
    return temp
    

story9/templates/story9/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Story 9</title>
    <link 
        rel="stylesheet" 
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
        crossorigin="anonymous">
    <script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static 'story9/index_style.css' %}">
    <!--<script src="{% static 'story8/javascript.js' %}"></script>-->
</head>
<body>
    <div class="body-container">
        {% if not user.is_authenticated %}
            <div class="anonim-content-container">
                <div class="anonim-message">
                    <h1>Hello stranger</h1>
                    <h2>Please log in <a href="{% url 'story9:login' %}">here</a> to see more of this website</h2>
                </div>
            </div>
        {% else %}
            <div class="login-bar">
                <div class="login-bar-content">
                    <div class="navigate-bar">
                        <div class="link-story">
                            <p><a href="{% url 'story1:index' %}">Story 1</a></p>
                        </div>
                        <div class="divider">|</div>
                        <div class="link-story">
                            <p><a href="{% url 'story3:homepage' %}">Story 3</a></p>
                        </div>
                        <div class="divider">|</div>
                        <div class="link-story">
                            <p><a href="{% url 'story7:index' %}">Story 7</a></p>
                        </div>
                        <div class="divider">|</div>
                        <div class="link-story">
                            <p><a href="{% url 'story8:index' %}">Story 8</a></p>
                        </div>
                    </div>
                    <div class="account-status">
                        <div class="account-action">
                            <div class="login-status">
                                <img class="user-icon" src="{% static 'story9/user.png' %}">
                                <p><span class="username-user">{{user.get_username}}</span></p>
                                <a href="{% url 'story9:logout' %}"><img class="logout-icon" src="{% static 'story9/exit.png' %}"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="user-content-container">
                <div class="user-data">
                    <h2 id="sapaan">Halo {{ user.get_username }}</h2>
                    {% if request.session.first_name == "-" and request.session.last_name == "-" %}
                        <h4>Nama: Data tidak tersedia</h4>
                    {% elif request.session.first_name == "-" %}
                        <h4>Nama: {{request.session.last_name}}</h4>
                    {% elif request.session.last_name == "-" %}
                        <h4>Nama: {{request.session.first_name}}</h4>
                    {% else %}
                        <h4>Nama: {{request.session.first_name}} {{request.session.last_name}}</h4>
                    {% endif %}
                    <h4>Peran: {{request.session.peran}}</h4>
                    <h4>Tanggal bergabung: {{request.session.date_joined}}</h4>
                    <h4>Terakhir login: {{request.session.last_login}}</h4>
                </div>
            </div>
        {% endif %}
    </div>
</body>
</html>

story9/templates/story9/login.html
{% load static %}
<!DOCTYPE html>
<html>   
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story9/login_style.css' %}">

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control" required='true'>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" required='true'>
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
                {% for message in messages %}
                <p id="messages">{{message}}</p>
                {% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'story9:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

story9/templates/story9/register.html
{% load static %}
<!DOCTYPE html>
<html>
    
<head>
	<title>Register Account</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'story9/register_style.css' %}">
     <script src="{% static 'story9/placeholder_register.js' %}"></script>
</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="form-content-container">
							<div class="input-group">
								<div class="input-group-append">
									<span class="input-group-text"><i class="fas fa-user"></i></span>
								</div>
								{{form.username}}
							</div>
							<div class="input-group">
								<div class="input-group-append">
									<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
								</div>
								{{form.email}}
							</div>
							<div class="input-group">
								<div class="input-group-append">
									<span class="input-group-text"><i class="fas fa-key"></i></span>
								</div>
								{{form.password1}}
							</div>
							<div class="input-group">
								<div class="input-group-append">
									<span class="input-group-text"><i class="fas fa-key"></i></span>
								</div>
								{{form.password2}}
							</div>
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
						   {% if form.errors %}
						   <div class="error-messages">
							   <ul>
							   {% for field in form %}
	   
								   {% for error in field.errors %}
										<li>{{field.label}}: {{ error|escape }}</li>
								   {% endfor %}
	   
							   {% endfor %}
								</ul>
							</div>
						   {% endif %}
					</form>
                    </div>
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'story9:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>

</body>
</html>