home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns =[
    path('', views.index, name='index')
]

story3/urls.py
from django.urls import path

from . import views

app_name = 'story3'

urlpatterns =[
    path('', views.homepage, name='homepage'),
    path('homepage/', views.homepage, name='homepage'),
    path('blogs/', views.blogs, name='blogs'),
    path('about_me/', views.about_me, name="about_me"),
    path('blogs/agustus17th/', views.agustus17th, name='blogs/agustus17th'),
    path('liat_matkul/', views.liat_matkul, name='liat_matkul'),
    path('tambah_matkul/', views.create_matkul, name="tambah_matkul"),
    path('matkul/<pk>/', views.matkul, name="matkul"),
    path('hapus_matkul/<pk>/', views.delete_matkul, name="hapus_matkul")
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include
from story8.views import data

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story1/', include('story1.urls')),
    path('story3/', include('story3.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    #path('data/', data),
]

story3/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model): 
    nama = models.CharField(max_length=30, null=False, blank=False)
    pengajar = models.CharField(max_length=30, null=False, blank=False)
    sks = models.CharField(max_length=1, null=False, blank=False)
    deskripsi = models.TextField(null=False, blank=False)
    semester = models.CharField(max_length=30, null=False, blank=False)
    ruang = models.CharField(max_length=30, null=False, blank=False)
    
    def __str__(self):
        return self.nama

story3/forms.py
from django import forms
from django.forms import ModelForm
from .models import Matkul
from django.core.exceptions import ValidationError

class MatkulForm(ModelForm):
    class Meta:
        model = Matkul
        fields = [
            'nama',
            'pengajar',
            'sks',
            'semester',
            'ruang',
            'deskripsi',
        ]
        widgets = {
            'nama' : forms.TextInput(attrs={
                'class' : 'form-control w-50',
                'placeholder' : 'Nama mata kuliah',
                'required' : 'true'}),
            'pengajar' : forms.TextInput(attrs={
                'class' : 'form-control w-50',
                'placeholder' : 'Nama dosen pengampu',
                'required' : 'true'}),
            'sks' : forms.TextInput(attrs={
                'class' : 'form-control w-50',
                'placeholder' : 'Jumlah SKS',
                'required' : 'true'}),
            'semester' : forms.TextInput(attrs={
                'class' : 'form-control w-50',
                'placeholder' : 'Term',
                'required' : 'true'}),
            'deskripsi' : forms.Textarea(attrs={
                'class' : 'form-control w-50',
                'placeholder' : 'Deskripsi mata kuliah',
                'required' : 'true'}),
            'ruang' : forms.TextInput(attrs={
                'class' : 'form-control w-50',
                'placeholder' : 'Ruang kuliah',
                'required' : 'true'}),
        }

    def clean_sks(self):
        sks = self.cleaned_data.get("sks")
        if not sks.isdigit():
            raise forms.ValidationError(sks +" is not a number, please insert a number for this field")
        return sks
    
    def clean_semester(self):
        semester = self.cleaned_data.get("semester")
        if not semester.isdigit():
            raise forms.ValidationError(semester + " is not a number, please insert a number for this field")
        return semester

story3/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import MatkulForm
from .models import Matkul

# Create your views here.
def homepage(request):
    return render(request, 'story3/homepage.html')

def blogs(request):
    return render(request, 'story3/blogs.html')

def about_me(request):
    return render(request, 'story3/profile.html')

def agustus17th(request):
    return render(request, 'story3/17-agustusan.html')

def liat_matkul(request):
    matkul = Matkul.objects.all()
    return render(request, 'story3/liat-matkul.html', {'matkuls' : matkul})

def create_matkul(request):
    form = MatkulForm()
    content = {'form' : form}

    if request.method == "POST":
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('story3:liat_matkul')
        else :
            form = MatkulForm()

    return render(request, 'story3/matkul-form.html', content)

def matkul(request, pk):
    matkul = Matkul.objects.get(id=pk)
    content = {'matkul' : matkul}
    return render(request, 'story3/matkul-detail.html', content)

def delete_matkul(request, pk):
    matkul = Matkul.objects.get(id=pk)
    
    if request.method == 'POST':
        matkul.delete()
        return redirect('story3:liat_matkul')

    content = {'matkul':matkul}
    return render(request, 'story3/matkul-delete.html', content)

story3/templates/story3/17-agustusan.html
{% extends 'story3/main.html' %}
{% block content %}
{% load static %}
<div class="container-fluid header_blog">
    <h2 class="text-center align-middle">This page is under construction :(</h2>
</div>
{% endblock %}

story3/templates/story3/blogs.html
{% extends 'story3/main.html' %}
{% block content %}

{% load static %}
<div class="container-fluid header_blog">
    <h2 class="text-center align-middle">This is my diary,<br>I want to tell you how my story <span>unfold</span></h2>
</div>
<div class="container">
    <div class="d-flex flex-column text-center pt-4">
        <div class="col-auto row py-3">
            <div class="col">
                <div class="container konten_satu">
                    <a href="{% url 'story3:blogs/agustus17th' %}">
                    <div class="d-flex flex-row p-2">
                        <div class="col-4">
                            <p id="judul_konten">Lomba 17 Agustus</p>
                        </div>
                        <div class="col-8">
                            <img src='{% static "story3/17an.jpg" %}' id="gambar_konten" alt="Foto 17an" class="img-thumbnail float-right">
                        </div>
                    </div>
                    </a>
                </div>
            </div>
            <div class="col">
                <div class="p-2 container konten_dua align-middle">
                    <p class="no_content">Cool story not avalaible yet :(</p>
                </div>
            </div>
        </div>
        <div class="col-auto row py-3">
            <div class="col">
                <div class="p-2 container konten_tiga">
                    <p class="no_content">Cool story not avalaible yet :(</p>
                </div>
            </div>
            <div class="col">
                <div class="p-2 container konten_empat">
                    <p class="no_content">Cool story not avalaible yet :(</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

story3/templates/story3/homepage.html
{% extends 'story3/main.html' %}
{% block content %}
{% load static %}
<div class="container-fluid" id="header">
    <div class="d-flex flex-column justify-content-center greeting align-middle m-auto">
        <h3>Hello there, welcome to my website</h3>
        <div class="row justify-content-md-center bw">
            <div class="col-md-auto second-greeting">
                <h3>I'm Zulfahri Haradi, a future <span>engineer</span></h3>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid align-content-center" id="konten_homepage">
    <div class="d-flex flex-column align-content-center align-middle">
        <div class="d-flex flex-column justify-content-md-center">
            <div class="col-md-auto text_content">
                <h3>I'm currently studying Computer Science</h3>
            </div>
            <div class="col-md-auto text_content">
                <h3>I'm confident at using these tools</h3>
            </div>
        </div>
        <div class="d-flex flex-column justify-content-md-center">
            <div class="col-md-auto gambar_content">
                <img src='{% static "story3/python.png" %}' id="python">
            </div>
            <div class="col-md-auto gambar_content">
                <img src='{% static "story3/java.png" %}' id="java">
            </div>
            <div class="col-md-auto gambar_content">
                <img src='{% static "story3/Rlogo.png" %}' id="rLogo">
            </div>
        </div>
    </div>
</div>
<div class="container-fluid px-0">
    <h5 id="contact_text">Get in touch with me:</h5>
    <div class="container text-center" id="footer">
        <div class="d-flex flex-row" id="icon_contact">
            <div class="col">
                <a href="https://www.instagram.com/hara.dih/"><img src='{% static "story3/instagram-logo.png" %}' id="logo_instagram"></a>
            </div>
            <div class="col">
                <a href="https://www.facebook.com/zulfahri.haradi.9/"><img src='{% static "story3/facebook.png" %}' id="logo_facebook"></a>
            </div>
            <div class="col">
                <a href="https://twitter.com/sukebeaurum55"><img src='{% static "story3/twitter.png" %}' id="logo_twitter"></a>
            </div>
        </div>
        <div id="footer_message">
            <p>Made by <span id="edgy">Aurum</span></p>
        </div>
    </div>
</div>

{% endblock %}

story3/templates/story3/liat-matkul.html
{% extends 'story3/main.html' %}
{% block content %}
{% load static %}
<div class="container-fluid header_blog">
    <h2 class="text-center align-middle">Mata kuliah di <span>Fasilkom</span></h2>
</div>
<div>
    <div class="row">
        <div class="col-md">
            <div class="card card-body">
                <h5>Mata Kuliah</h5>
            </div>
            <div class="card card-body">
                {% if matkuls %}
                    <table class="table">
                        <tr>
                            <th>Nama</th>
                            <th>Dosen pengajar</th>
                            <th>SKS</th>
                            <th>Delete</th>
                        </tr>
                            {% for matkul in matkuls %}
                                <tr>
                                    <td><a href="{% url 'story3:matkul' matkul.id %}">{{matkul.nama}}</a></td>
                                    <td>{{matkul.pengajar}}</td>
                                    <td>{{matkul.sks}}</td>
                                    <td><a href="{% url 'story3:hapus_matkul' matkul.id %}" class="btn btn-md btn-danger">Hapus</a></td>
                                </tr>
                            {% endfor %}
                    </table>
                {% else %}
                <div class="row mt-4">
                    <div class="col-3"></div>
                    <div class="card-title text-center col-6">
                        Maaf, tidak ada mata kuliah yang tersedia
                    </div>
                    <div class="col-3"></div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <a class="btn btn-primary btn-lg btn-block active" aria-pressed="true" href="{% url 'story3:tambah_matkul' %}">
            Tambah Matkul
        </a>
    </div>
</div>
{% endblock %}

story3/templates/story3/main.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story3/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Bitter&display=swap" rel="stylesheet">
    <title>Story 5 PPW</title>
</head>
<body>
    <div class="container rounded-bottom fixed-top" id="container_navbar">
        <nav class="navbar navbar-expand-sm">
            <ul class="navbar-nav justify-content-center mx-auto">
                <li class="nav-item mx-auto">
                    <a class="nav-link py-0" href="{% url 'story3:homepage' %}">Home</a>
                </li>
                <li class="nav-item mx-auto">
                    <a class="nav-link py-0" href="{% url 'story3:liat_matkul' %}">Mata kuliah</a>
                </li>
                <li class="nav-item mx-auto">
                    <a class="nav-link py-0" href="{% url 'story1:index' %}">Story 1</a>
                </li>
                <li>
                    <a class="navbar-brand py-0" href="{% url 'story3:homepage' %}">
                        <img src='{% static "story3/logo.png" %}' alt="logo" id="foto_logo">
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link py-0" href="{% url 'story3:blogs' %}">Blogs</a>
                </li>
                <li class="nav-item text-center about-me">
                    <a class="nav-link py-0" href="{% url 'story3:about_me' %}">About Me</a>
                </li>
            </ul>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

story3/templates/story3/matkul-delete.html
{% extends 'story3/main.html' %}
{% block content %}
{% load static %}
<div class="container-fluid header_blog">
    <h2 class="text-center align-middle">Tambah <span>matkul</span></h2>
</div>
<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="form-group p-4 text-center">
                <form action="{% url 'story3:hapus_matkul' matkul.id %}" method="POST">
                    {% csrf_token %}
                    <div class="col-md card-body">
                        <h4 class="text">Hapus {{matkul}} dari daftar?</h4>
                        <div class="d-flex justify-content-center pt-2">
                            <div class="px-2">
                                <a class="btn btn-secondary" href="{% url 'story3:liat_matkul' %}">Tidak</a>
                            </div>
                            <div class="px-2">
                                <input type="submit" class="btn btn-danger" value="Ya">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
</div>
{% endblock %}

story3/templates/story3/matkul-detail.html
{% extends 'story3/main.html' %}
{% block content %}
{% load static %}
<div class="container-fluid header_blog">
    <h2 class="text-center align-middle">{{ matkul.nama }}</h2>
</div>
<div class="row m-4">
    <div class="col-5">
        <div class="card-body border border-dark rounded-sm">
            <h5 class="card-title text-center">
                Pengajar
            </h5>
            <p class="card-text text-center">
                {{ matkul.pengajar }}
            </p>
        </div>
    </div>
    <div class="col-3">
        <div class="card-body border border-dark rounded-sm">
            <h5 class="card-title text-center">
                Ruang Kelas
            </h5>
            <p class="card-text text-center">
                {{ matkul.ruang }}
            </p>
        </div>
    </div>
    <div class="col-2">
        <div class="card-body border border-dark rounded-sm">
            <h5 class="card-title text-center">
                Jumlah SKS
            </h5>
            <p class="card-text text-center">
                {{ matkul.sks }}
            </p>
        </div>
    </div>
    <div class="col-2">
        <div class="card-body border border-dark rounded-sm">
            <h5 class="card-title text-center">
                Semester
            </h5>
            <p class="card-text text-center">
                {{ matkul.semester }}
            </p>
        </div>
    </div>
</div>
<div class="container-md h-100">
    <div class="row align-items-center justify-content-center">
        <div class="row col-3"></div>
        <div class="row col-6">
            <div class="card-body border border-dark rounded-sm">
                <h5 class="card-title text-center">
                    Deskripsi
                </h5>
                <p class="card-text text-center text-justify">
                    {{ matkul.deskripsi }}
                </p>
            </div>
        </div>
        <div class="row col-3"></div>
    </div>
</div>
<div class="container pt-5"  id="back_home">
    <div class="row justify-content-center align-items-end">
        <div class="row col-5"></div>
        <div class="row col-2 justify-content-center">
            <a href="{% url 'story3:liat_matkul' %}" class="btn btn-primary align-self-end text-center homee">Kembali</a>
        </div>
        <div class="row col-5"></div>
    </div>
</div>



{% endblock %}

story3/templates/story3/matkul-form.html
{% extends 'story3/main.html' %}
{% block content %}
{% load static %}
<div class="container-fluid header_blog">
    <h2 class="text-center align-middle">Tambah <span>matkul</span></h2>
</div>
<div class="form-group p-4">
    <form method="POST">
        {% csrf_token %}
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        {% endif %}
        {{form.as_p}}
        <div class="d-flex justify-content-start">
            <div class="mr-2">
                <input type="submit" class="btn btn-primary" value="Submit"">
            </div>
            <div class="ml-2">
                <a href="{% url 'story3:liat_matkul' %}" class="btn btn-secondary">Kembali</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

story3/templates/story3/profile.html
{% extends 'story3/main.html' %}
{% block content %}
{% load static %}
    <div class="container-md" id="header_profile">
        <div class="row justify-content-md-center">
            <div class="col-md-3">
                <img src='{% static "story3/my_photo.jpg" %}' id="my_photo">
            </div>
            <div class="col-md-7">
                <div class="d-flex flex-column" id="my_data">
                    <div class="col">
                        <h1>Zulfahri Haradi Hidayatullah</h1>
                    </div>
                    <div class="col univ_ind">
                        <h3>Undergraduate Student at Computer Science Faculty
                            <br><span>University of Indonesia</span></h3>
                    </div>
                    <div class="col">
                        <h3>Class of 2019</h3>
                    </div>
                </div>
            </div>
            <div class="col-md-2 align-self-center pt-2">
                <div class="d-flex flex-column medsos_profile">
                    <div class="col py-2">
                        <a href="https://www.instagram.com/hara.dih/"><img src='{% static "story3/instagram-logo.png" %}' id="logo_instagram"></a>
                    </div>
                    <div class="col py-2">
                        <a href="https://www.facebook.com/zulfahri.haradi.9/"><img src='{% static "story3/facebook.png" %}' id="logo_facebook"></a>
                    </div>
                    <div class="col py-2">
                        <a href="https://twitter.com/sukebeaurum55"><img src='{% static "story3/twitter.png" %}' id="logo_twitter"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-md float-left">
        <div class="row justify-content-between pt-3 px-3 align-self-center">
            <div class="col deskripsi_tambahan">
                <p>
                    I’m an ordinary college student that you can find everywhere.
                    I love Japanese culture, stuff like anime, manga, you name it.
                    I thought that i would find a deen of weebs on Faculty of Computer Science but i was wrong. 
                    I enjoyed my time here though.          
                </p>
            </div>
            <div class="col education">
                <h3><b>Education</b> <i class='fas fa-graduation-cap'></i></h3>
                <ul class="list_pendidikan">
                    <li>2007 - 2013 SDN Panaragan Kidul</li>
                    <li>2013 - 2016 SMPN 7 Bogor</li>
                    <li>2016 - 2019 SMAN 5 Bogor</li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

story3/templates/story3/temp.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'story3/css/style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Bitter&display=swap" rel="stylesheet"> 
    <title>Story 3 PPW</title>
</head>
<body>
    <div class="container rounded-bottom fixed-top" id="container_navbar">
        <nav class="navbar navbar-expand-sm">
            <ul class="navbar-nav justify-content-center mx-auto">
                <li class="nav-item mx-auto">
                    <a class="nav-link py-0" href="#">Home</a>
                </li>
                <li class="nav-item mx-auto">
                    <a class="nav-link py-0" href="#">Story</a>
                </li>
                <li>
                    <a class="navbar-brand py-0" href="home.html">
                        <img src='{% static "story3/images/logo.png" %}' alt="logo" id="foto_logo">
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link py-0" href="blog.html">Blogs</a>
                </li>
                <li class="nav-item text-center about-me">
                    <a class="nav-link py-0" href="profile.html">About Me</a>
                </li>
            </ul>

        </nav>
    </div>
    <div class="container-fluid" id="header">
        <div class="d-flex flex-column justify-content-center greeting align-middle m-auto">
            <h3>Hello there, welcome to my website</h3>
            <div class="row justify-content-md-center bw">
                <div class="col-md-auto second-greeting">
                    <h3>I'm Zulfahri Haradi, a future <span>engineer</span></h3>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid align-content-center" id="konten_homepage">
        <div class="d-flex flex-column align-content-center align-middle">
            <div class="d-flex flex-column justify-content-md-center">
                <div class="col-md-auto text_content">
                    <h3>I'm currently studying Computer Science</h3>
                </div>
                <div class="col-md-auto text_content">
                    <h3>I'm confident at using these tools</h3>
                </div>
            </div>
            <div class="d-flex flex-column justify-content-md-center">
                <div class="col-md-auto gambar_content">
                    <img src='{% static "story3/images/python.png" %}' id="python">
                </div>
                <div class="col-md-auto gambar_content">
                    <img src='{% static "story3/images/java.png" %}' id="java">
                </div>
                <div class="col-md-auto gambar_content">
                    <img src='{% static "story3/images/Rlogo.png" %}' id="rLogo">
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid px-0">
        <h5 id="contact_text">Get in touch with me:</h5>
        <div class="container text-center" id="footer">
            <div class="d-flex flex-row" id="icon_contact"> 
                <div class="col">
                    <a href="https://www.instagram.com/hara.dih/"><img src='{% static "story3/images/instagram-logo.png" %}' id="logo_instagram"></a>
                </div>
                <div class="col">
                    <a href="https://www.facebook.com/zulfahri.haradi.9/"><img src='{% static "story3/images/facebook.png" %}' id="logo_facebook"></a>
                </div>
                <div class="col">
                    <a href="https://twitter.com/sukebeaurum55"><img src='{% static "story3/images/twitter.png" %}' id="logo_twitter"></a>
                </div>
            </div>
            <div id="footer_message">
                <p>Made by <span id="edgy">Aurum</span></p>
            </div>
        </div>
    </div>
</body>
</html>