home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name="index"),
]

story1/urls.py
from django.urls import path

from . import views

app_name = 'story1'

urlpatterns =[
    path('', views.index, name='index')
]

storyppw/urls.py
from django.contrib import admin
from django.urls import path, include
from story8.views import data

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story1/', include('story1.urls')),
    path('story3/', include('story3.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    #path('data/', data),
]

story1/models.py
from django.db import models

# Create your models here.

story1/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'story1/test.html')

story1/templates/story1/test.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'story1/style.css' %}">
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    <title>Story 1 PPW</title>
</head>
<body>
    <div id="block1">
        <table>
            <tr>
                <td>
                    <img src="{% static 'story1/my_photo.jpg' %}" alt="Zulfahri Haradi Hidayatullah" id="myphoto"/> 
                </td>
                <td id="rowdata">
                    <h1 id="nama">Zulfahri Haradi Hidayatullah</h1>
                    <h2 id="npm">NPM : 1906398572</h2>
                    <p id="angkatan">Fakultas Ilmu Komputer <i class='fas fa-laptop-code'></i>
                        <br> Universitas Indonesia Angkatan 2019</p>
                    <p id="deskripsi">Saya adalah seseorang yang memiliki tingkat daya tarik terhadap berbagai hal
                        yang rendah, khususnya terhadap web developing:( tapi saya akan berusaha sekuat
                        tenaga untuk memanjakan mata para pengunjung halaman ini :D </p>
                </td>
            </tr>
        </table>
    </div>
    <div id="block2">
        <h2>Pendidikan <i class='fas fa-graduation-cap'></i></h2>
        <table class="pendidikan">
            <tr><td>- SDN Panaragan Kidul</td></tr>
            <tr><td>- SMPN 7 Bogor</td></tr>
            <tr><td>- SMAN 5 Bogor</td></tr>
        </table>
        <h2>Media Sosial <i class="far fa-address-book"></i></h2>
        <table class="sosmed">
            <tr>
                <td>
                    <a href="https://www.instagram.com/hara.dih/" class="button"><i class="fab fa-instagram" ></i></a>
                </td>
                <td>
                    <a href="https://www.facebook.com/zulfahri.haradi.9/" class="button"><i class="fab fa-facebook" ></i></a>
                </td>
                <td>
                    <a href="https://twitter.com/sukebeaurum55" class="button"><i class="fab fa-twitter" ></i></a>
                </td>
            </tr>
        </table>
    </div>
    <p class="home"><a href="{% url 'home:index' %}">Kembali ke halaman utama</a></p>
</body>
</html>